import * as vscode from 'vscode';
import * as path from 'path';

export async function generateMockDataCommand(modelName?: string): Promise<void> {
    const editor = vscode.window.activeTextEditor;
    if (!modelName && editor) {
        const text = editor.document.getText();
        const match = text.match(/class\s+([A-Za-z0-9_]+)\s*\((?:ForensicModel|BaseModel|ForensicDocument)\)/);
        if (match) {
            modelName = match[1];
        }
    }

    if (!modelName) {
        modelName = await vscode.window.showInputBox({
            prompt: 'Enter Pydantic DB Model class name to generate Mock / Seed Data for:',
            placeHolder: 'e.g. AnalyticsEvent, User, Document'
        });
    }

    if (!modelName) {
        return;
    }

    const countInput = await vscode.window.showInputBox({
        prompt: 'Number of synthetic seed records to generate:',
        value: '50'
    });

    const count = parseInt(countInput || '50', 10);

    const folder = vscode.workspace.workspaceFolders ? vscode.workspace.workspaceFolders[0].uri.fsPath : '.';
    const seedFilePath = path.join(folder, 'scripts', `seed_${modelName.toLowerCase()}.py`);

    const code = `"""
Automated Synthetic Mock Data & Seed Generator for ${modelName}
Generated by WDatabase Tools (wdatabase-vscode)
Author: William Steve Rodriguez Villamizar (Wisrovi)
"""
import random
from datetime import datetime, timedelta
# Import your model:
# from models import ${modelName}

def generate_mock_${modelName.toLowerCase()}_records(n: int = ${count}):
    """Generate ${count} synthetic records for testing and development"""
    records = []
    base_time = datetime.utcnow()
    
    print(f"Generating {n} synthetic mock records for ${modelName}...")
    for i in range(1, n + 1):
        record = {
            "id": i,
            "title": f"${modelName}_Sample_{i}",
            "name": f"synthetic_entity_{i}",
            "value": round(random.uniform(10.0, 999.0), 2),
            "status": 1,
            "created_at": (base_time - timedelta(minutes=i * 5)).isoformat(),
        }
        records.append(record)
    
    print(f"Generated {len(records)} records successfully.")
    return records

if __name__ == "__main__":
    seeds = generate_mock_${modelName.toLowerCase()}_records()
    print("Sample record 0:", seeds[0])
`;

    const uri = vscode.Uri.file(seedFilePath);
    await vscode.workspace.fs.writeFile(uri, Buffer.from(code, 'utf8'));
    const doc = await vscode.workspace.openTextDocument(uri);
    await vscode.window.showTextDocument(doc);

    vscode.window.showInformationMessage(`🌱 Seed script created for ${modelName}: ${path.basename(seedFilePath)}`);
}
